"""test migration

Revision ID: 7768e87e8fd9
Revises: 0eb579683bb7
Create Date: 2024-07-07 16:29:01.472806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7768e87e8fd9'
down_revision: Union[str, None] = '0eb579683bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balance', sa.Numeric(), nullable=False))
    op.add_column('persons', sa.Column('balance', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'balance')
    op.drop_column('accounts', 'balance')
    # ### end Alembic commands ###
